etasl_node:
    ros__parameters:
        task_specification_file: "/home/santiregui/ros2_ws/src/etasl_ros2/etasl/move_cartesianspace.lua"
        jointnames: ["shoulder_pan_joint","shoulder_lift_joint","elbow_joint","wrist_1_joint","wrist_2_joint","wrist_3_joint"]