etasl_node:
    ros__parameters:
        jointnames: ["shoulder_pan_joint","shoulder_lift_joint","elbow_joint","wrist_1_joint","wrist_2_joint","wrist_3_joint"]
        # task_specification_file: "/workspaces/colcon_ws/src/etasl_ros2/etasl/move_cartesianspace.lua"