---
--- Operations on values in eTaSL
---
--- value : similar to a number, can have different types:
---          Vector, Rotation, Frame, Twist, Wrench, number, Quaternion
--- expression:  an expression graph.  can have different types:
---          expression_vector, expression_rotation, expression_frame,
---          expression_twist, expression_wrench, expression_quaternion
---
--- expressions typically end up in the task definition stored in the eTaSL ctx ("context")
--- variable and used during execution in constraints, inputs, outputs and monitors.
---

